// window-bridge.js
// Phase 0: every top-level function in main.js is exposed on `window` so the
// 75+ inline onclick/onchange/... attributes in index.html keep working
// unchanged now that main.js runs as an ES module (module scope does not
// leak to `window` the way a classic <script> did).
//
// This list will narrow over later phases as functions move into real
// feature modules and get their own smaller, purpose-specific bridging
// (see modularization plan, section 2 and section 5, Phase 7).
//
// Phase 8: main.js ↔ feature-module import cycles are gone — every feature
// file now imports shared helpers (showToast, t, renderAll, switchTab, etc.)
// straight from their real owning module instead of back through main.js.
// This file is the sole remaining importer of './main.js', by design: it
// exists purely to flatten main.js's re-exports onto `window` for the
// inline onclick/onchange attributes in index.html.

import {
  CS, addCustomPaymentMethod, addPricingTier, addProduct,
  refreshDeliveryAssignments, transitionDeliveryAssignmentForOrder,
  addTable, addVolumeDiscountTier, addWarehouseLocation, loadOrganizationLocations, selectOrganizationLocation, selectWarehouseLocation, openOrganizationLocationModal, closeOrganizationLocationModal, saveOrganizationLocationModal, advanceFulfillmentOrder,
  applyBusinessModelUI, applyLogisticsUI, applyRolePermissions, applyStockChange,
  applyStoreBranding, applyWarehouseUI, applyWholesaleUI, cancelProductEdit,
  capitalize, changeLanguage, changeQty, checkoutTelegramWebApp,
  clearMarketSearch, clearSearch, closeAccountModal, closeImageModal,
  closeMarketCheckoutModal, closeModifierNoteModal, closeMoreSheet, closePaymentProofModal,
  closePinModal, closeReceiveModal, closeStockAdjustModal, closeTableModal,
  closeTableTransferModal, compressImage, confirmOrderWithProof, confirmTransfer,
  copyReceipt, createKitchenNode, createTicketNode, cycleTableStatus,
  deleteOrder, advanceMarketplaceOrderStatus, cancelMarketplaceOrder, downloadImageFile, drawCanvasReceipt, editTable,
  effectiveUnitPrice, escapeAttr, escapeHtml, exportLedgerData,
  fallbackCopy, fetchMarketplaceListings, fetchRemoteCatalogAndBranding, finalizeOrderDelete,
  finalizeServed, formatBytes, formatElapsed, formatElapsedShort,
  formatReceiptText, fulfillmentStatusLabel, generateAndShareImageReceipt, getB2BAccountById,
  getBusinessModel, getLang, getLowStockProducts, getNichePreset,
  getOrderById, getOutOfStockProducts, getPricingTierById, getVolumeDiscountForQty,
  handleEditProdImageSelect, handleImageModalBackdrop, handleNewProdImageSelect, handleLocalStationJoinCode,
  handleToastUndo, hasPermission, hydrateFromIndexedDB, idbDelete,
  idbGet, idbGetAll, idbOpen, idbSet,
  isFulfillmentFinal, isLogisticsEnabled, isRestaurant, isStockTracked,
  isVolumeDiscountEnabled, isWarehouseEnabled, isWholesaleEnabled, kitchenBodyHtml,
  kitchenNodeClassName, ledgerIsMigrated, ledgerMarkMigrated, loadJSON,
  migrateOneKey, modifierNoteMarkup, nextFulfillmentStatus, onBusinessModelChange,
  onCashInput, onCurrencyCodeChange, onMarketSearchInput, onNewProdCategoryChange,
  onNicheChange, onOrderAccountChange, onOrderCourseChange, onOrderPayMethodChange,
  onSearchInput, onStockAdjustProductChange, onVolumeDiscountToggle, onWarehouseToggle,
  onWholesaleToggle, openAccountModal, openImageModal, openMarketCheckoutModal,
  openModifierNoteModal, openMoreSheet, openPaymentProofModal, openPinModal,
  openProductImageModal, openReceiveModal, openSettings, openStockAdjustModal,
  openTableModal, optimisticMarkServed, patchList, patchProductCard,
  printReceipt, productPriceMarkup, reapplyConfigDefaults, recordTelegramSentOrder,
  removeAccount, removeKitchenNode, removePaymentMethod, removePricingTier,
  removeProduct, removeTable, removeTicketNode, removeVolumeDiscountTier,
  removeWarehouseLocation, bootstrapTenantAuth, closeOnboarding, createOnboardingTenant, selectOnboardingTenant, pairThisDevice, showPairing, createDevicePairing, showJoinByInvite, submitStaffInvite, createStaffInvite, addOnboardingProduct, skipOnboardingProduct, finishOnboarding, submitSettingsInvite, switchActiveTenant, renderAccountTierOptions, renderAccounts, renderCustomers, openCustomerModal, closeCustomerModal, saveCustomerModal, renderAll,
  renderBrand, renderCatalog, renderCategoryPills, renderSellerHome, renderDailySummary, renderStorefrontBranding, updateBrandingPreview, saveStorefrontBranding,
  renderKitchen, renderLogistics, renderMarketplace, renderNicheSelect,
  renderOrderAccountSelect, renderOrderCourseSelect, renderOrderFulfillmentPicker, renderOrderTableSelect,
  renderPaymentMethodsSettings, renderPricingTiersSettings, renderProductFormSelects, renderProducts,
  renderQueue, renderStatus, renderTables, renderVolumeDiscountSettings,
  renderWarehouseInventory, renderWarehouseLocationsList, renderWarehouseReceiving, renderWarehouseTransactions,
  requestLedgerStoragePersistence, runLedgerMigration, sanitizeId, sanitizeRemoteListings,
  sanitizeRemoteProducts, saveAccountModal, saveB2BAccounts, saveJSON,
  saveModifierNote, saveOrder, savePricingTiers, saveProductEdit,
  saveReceiveModal, saveSettings, saveStockAdjustModal, saveStockTransactions,
  saveTableModal, saveTables, saveVolumeDiscountTiers, saveWarehouseLocations,
  scrollToOrderSummary, setCashTendered, setCategory, setFulfillmentType,
  setKitchenPriority, setKitchenSort, setKitchenStatus, setMarketCategory,
  setOrderViewMode, shareReceipt, showToast, showUndoToast,
  startKitchenTimer, startProductEdit, stockBadgeMarkup, stopKitchenTimer,
  submitMarketplaceOrder, switchTab, switchWarehouseSubtab, syncCatalog,
  syncNow, syncOrders, t, ticketInnerHtml,
  toggleNewProdTag, togglePaymentMethodEnabled, transferTable, txItemMarkup,
  uid, undoDeleteOrder, undoMarkServed, updateCartStickyBar,
  updateChangeDisplay, updateI18n, updateKitchenBadge, updateKitchenNode,
  updateKitchenTimer, updateMarketCartQty, updateMultiCartBar, updateNicheFieldVisibility,
  updateOrderSummary, updatePaymentMethodDetails, updateStorageInfoDisplay, updateTicketNode,
  updateViewToggleButtons, verifyPinAndSwitch, viewPaymentProof, warehouseProductOptions,
  renderDeviceList, revokeDeviceInList
} from './main.js';

if (typeof window !== 'undefined') {
  Object.assign(window, {
  CS, addCustomPaymentMethod, addPricingTier, addProduct,
  addTable, addVolumeDiscountTier, addWarehouseLocation, loadOrganizationLocations, selectOrganizationLocation, selectWarehouseLocation, openOrganizationLocationModal, closeOrganizationLocationModal, saveOrganizationLocationModal, advanceFulfillmentOrder,
  applyBusinessModelUI, applyLogisticsUI, applyRolePermissions, applyStockChange,
  applyStoreBranding, applyWarehouseUI, applyWholesaleUI, cancelProductEdit,
  capitalize, changeLanguage, changeQty, checkoutTelegramWebApp,
  clearMarketSearch, clearSearch, closeAccountModal, closeImageModal,
  closeMarketCheckoutModal, closeModifierNoteModal, closeMoreSheet, closePaymentProofModal,
  closePinModal, closeReceiveModal, closeStockAdjustModal, closeTableModal,
  closeTableTransferModal, compressImage, confirmOrderWithProof, confirmTransfer,
  copyReceipt, createKitchenNode, createTicketNode, cycleTableStatus,
  deleteOrder, advanceMarketplaceOrderStatus, cancelMarketplaceOrder, downloadImageFile, drawCanvasReceipt, editTable,
  effectiveUnitPrice, escapeAttr, escapeHtml, exportLedgerData,
  fallbackCopy, fetchMarketplaceListings, fetchRemoteCatalogAndBranding, finalizeOrderDelete,
  finalizeServed, formatBytes, formatElapsed, formatElapsedShort,
  formatReceiptText, fulfillmentStatusLabel, generateAndShareImageReceipt, getB2BAccountById,
  getBusinessModel, getLang, getLowStockProducts, getNichePreset,
  getOrderById, getOutOfStockProducts, getPricingTierById, getVolumeDiscountForQty,
  handleEditProdImageSelect, handleImageModalBackdrop, handleNewProdImageSelect, handleLocalStationJoinCode,
  handleToastUndo, hasPermission, hydrateFromIndexedDB, idbDelete,
  idbGet, idbGetAll, idbOpen, idbSet,
  isFulfillmentFinal, isLogisticsEnabled, isRestaurant, isStockTracked,
  isVolumeDiscountEnabled, isWarehouseEnabled, isWholesaleEnabled, kitchenBodyHtml,
  kitchenNodeClassName, ledgerIsMigrated, ledgerMarkMigrated, loadJSON,
  migrateOneKey, modifierNoteMarkup, nextFulfillmentStatus, onBusinessModelChange,
  onCashInput, onCurrencyCodeChange, onMarketSearchInput, onNewProdCategoryChange,
  onNicheChange, onOrderAccountChange, onOrderCourseChange, onOrderPayMethodChange,
  onSearchInput, onStockAdjustProductChange, onVolumeDiscountToggle, onWarehouseToggle,
  onWholesaleToggle, openAccountModal, openImageModal, openMarketCheckoutModal,
  openModifierNoteModal, openMoreSheet, openPaymentProofModal, openPinModal,
  openProductImageModal, openReceiveModal, openSettings, openStockAdjustModal,
  openTableModal, optimisticMarkServed, patchList, patchProductCard,
  printReceipt, productPriceMarkup, reapplyConfigDefaults, recordTelegramSentOrder,
  removeAccount, removeKitchenNode, removePaymentMethod, removePricingTier,
  removeProduct, removeTable, removeTicketNode, removeVolumeDiscountTier,
  removeWarehouseLocation, bootstrapTenantAuth, closeOnboarding, createOnboardingTenant, selectOnboardingTenant, pairThisDevice, showPairing, createDevicePairing, showJoinByInvite, submitStaffInvite, createStaffInvite, addOnboardingProduct, skipOnboardingProduct, finishOnboarding, submitSettingsInvite, switchActiveTenant, renderAccountTierOptions, renderAccounts, renderCustomers, openCustomerModal, closeCustomerModal, saveCustomerModal, renderAll,
  renderBrand, renderCatalog, renderCategoryPills, renderSellerHome, renderDailySummary, renderStorefrontBranding, updateBrandingPreview, saveStorefrontBranding,
  renderKitchen, renderLogistics, renderMarketplace, renderNicheSelect,
  renderOrderAccountSelect, renderOrderCourseSelect, renderOrderFulfillmentPicker, renderOrderTableSelect,
  renderPaymentMethodsSettings, renderPricingTiersSettings, renderProductFormSelects, renderProducts,
  renderQueue, renderStatus, renderTables, renderVolumeDiscountSettings,
  renderWarehouseInventory, renderWarehouseLocationsList, renderWarehouseReceiving, renderWarehouseTransactions,
  requestLedgerStoragePersistence, runLedgerMigration, sanitizeId, sanitizeRemoteListings,
  sanitizeRemoteProducts, saveAccountModal, saveB2BAccounts, saveJSON,
  saveModifierNote, saveOrder, savePricingTiers, saveProductEdit,
  saveReceiveModal, saveSettings, saveStockAdjustModal, saveStockTransactions,
  saveTableModal, saveTables, saveVolumeDiscountTiers, saveWarehouseLocations,
  scrollToOrderSummary, setCashTendered, setCategory, setFulfillmentType,
  setKitchenPriority, setKitchenSort, setKitchenStatus, setMarketCategory,
  setOrderViewMode, shareReceipt, showToast, showUndoToast,
  startKitchenTimer, startProductEdit, stockBadgeMarkup, stopKitchenTimer,
  submitMarketplaceOrder, switchTab, switchWarehouseSubtab, syncCatalog,
  syncNow, syncOrders, t, ticketInnerHtml,
  toggleNewProdTag, togglePaymentMethodEnabled, transferTable, txItemMarkup,
  uid, undoDeleteOrder, undoMarkServed, updateCartStickyBar,
  updateChangeDisplay, updateI18n, updateKitchenBadge, updateKitchenNode,
  updateKitchenTimer, updateMarketCartQty, updateMultiCartBar, updateNicheFieldVisibility,
  updateOrderSummary, updatePaymentMethodDetails, updateStorageInfoDisplay, updateTicketNode,
  updateViewToggleButtons, verifyPinAndSwitch, viewPaymentProof, warehouseProductOptions, selectWarehouseLocation,
  renderDeviceList, revokeDeviceInList
  });
}
