#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

required_major=24
actual_major="$(node -p 'process.versions.node.split(".")[0]')"
if (( actual_major < required_major )); then
  echo "FAIL: supported-runtime gate requires Node >= ${required_major}; found $(node --version)."
  echo "INFO: run the release check under the deployment/runtime image before tagging a release."
  exit 2
fi

bash scripts/phase0-baseline.sh
node phase0/golden-regression.mjs

archive_sha="$(awk '{print $1}' phase0/SOURCE-ARCHIVE.sha256)"
manifest="phase0/RELEASE-MANIFEST.md"
{
  echo "# Sellify Phase 0 Release Manifest"
  echo
  echo "Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "Source archive SHA-256: $archive_sha"
  echo "Node runtime: $(node --version)"
  echo "Golden regression: PASS"
  echo "Backup/restore verification: PASS (included in golden regression)"
  echo "Migration idempotency: PASS (included in golden regression)"
  echo
  echo "## Release rule"
  echo "This manifest is valid only when generated by scripts/phase0-release-check.sh under Node >=24."
  echo "Do not tag a production release from a runtime-gate failure."
} > "$manifest"

sha256sum phase0/RELEASE-MANIFEST.md > phase0/RELEASE-MANIFEST.sha256

echo "PASS: Phase 0 release-control check"
echo "PASS: Release manifest written to phase0/RELEASE-MANIFEST.md"
