import { config, b2bAccounts, products, currentStaff } from '../state.js';
import { hasPermission } from '../auth/permissions.js';
import { showToast } from '../ui/toast.js';
import { escapeHtml } from '../utils/index.js';

function baseUrl(){return (config.syncUrl||window.location.origin).replace(/\/$/,'');}
function headers(){return {'Content-Type':'application/json',Authorization:'Bearer '+config.sessionToken};}
function canManage(){return !!config.sessionToken&&!!config.chatId&&hasPermission(currentStaff?.role||config.tenantRole||config.role||'owner','b2b:pricing:manage');}
async function api(path,options={}){const res=await fetch(baseUrl()+path,{...options,headers:{...headers(),...(options.headers||{})}});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data?.error?.message||('Request failed ('+res.status+')'));return data;}
function customerOptions(){return '<option value="">Select business customer…</option>'+b2bAccounts.map(c=>'<option value="'+c.id+'">'+escapeHtml(c.business_name)+'</option>').join('');}
function productOptions(){return '<option value="">Select product…</option>'+products.map(p=>'<option value="'+escapeHtml(p.id)+'">'+escapeHtml(p.name||p.id)+' — '+String(p.price??'')+'</option>').join('');}
export async function loadCustomerPricing(){const list=document.getElementById('b2bCustomerPricingList');if(!list||!config.chatId||!config.sessionToken)return;list.innerHTML='<div class="hint">Loading canonical customer pricing…</div>';try{const data=await api('/tenants/'+encodeURIComponent(config.chatId)+'/b2b/pricing?limit=200');const rows=data.pricing||[];list.innerHTML=rows.length?rows.map(r=>'<div class="table-card"><div class="account-name">'+escapeHtml(r.customerName||r.customerId)+' · '+escapeHtml(r.productName||r.productId)+'</div><div class="account-tier-badge">'+escapeHtml(String(r.priceMinor))+' '+escapeHtml(r.currency)+' · '+escapeHtml(r.status)+'</div><div class="hint">'+escapeHtml(r.updatedAt||r.updated_at||'')+'</div></div>').join(''):'<div class="empty">No customer-specific pricing rules.</div>';}catch(e){list.innerHTML='<div class="hint">'+escapeHtml(e.message||'Could not load pricing rules.')+'</div>';}}
export async function saveCustomerPricing(){if(!canManage()){showToast('B2B pricing management permission required');return;}const customerId=document.getElementById('b2bPricingCustomer')?.value||'';const productId=document.getElementById('b2bPricingProduct')?.value||'';const priceMinor=Number(document.getElementById('b2bPricingPrice')?.value);const reason=document.getElementById('b2bPricingReason')?.value.trim()||'';if(!customerId||!productId||!Number.isInteger(priceMinor)||priceMinor<0){showToast('Select a customer and product and enter a valid integer price');return;}try{await api('/tenants/'+encodeURIComponent(config.chatId)+'/b2b/pricing',{method:'POST',body:JSON.stringify({customerId,productId,priceMinor,reason})});showToast('Customer pricing saved ✓');await loadCustomerPricing();}catch(e){showToast(e.message||'Could not save customer pricing');}}
export function renderCustomerPricingPanel(){const panel=document.getElementById('b2bCustomerPricingPanel');if(!panel)return;if(!config.sessionToken||!config.chatId){panel.style.display='none';return;}panel.style.display='block';panel.innerHTML='<div class="settings-section-label">Customer-specific B2B pricing</div><div class="sync-note">Prices are stored and enforced by the canonical B2B pricing API. This panel does not create a local pricing ledger.</div><div class="customer-fields" style="margin-bottom:12px;"><select id="b2bPricingCustomer">'+customerOptions()+'</select><select id="b2bPricingProduct">'+productOptions()+'</select><input id="b2bPricingPrice" type="number" min="0" step="1" placeholder="Price (minor units)"><input id="b2bPricingReason" type="text" placeholder="Reason (optional)"><button id="b2bPricingSave" class="btn-secondary" type="button" style="width:auto;padding:8px 12px;">Save price</button></div><div id="b2bCustomerPricingList" class="tables-grid"></div>';document.getElementById('b2bPricingSave')?.addEventListener('click',saveCustomerPricing);loadCustomerPricing();}